// RF-0307: datos quemados para prototipo del centro de notificaciones
import 'notification_model.dart';

final mockNotifications = <NotificationModel>[
  NotificationModel(
    id: 'n001',
    title: 'Emergencia hídrica en Oeste',
    body:
        'Nivel del río superó umbral de Emergencia (+4.1 m). Evita la zona ribereña.',
    barrio: 'Oeste',
    type: NotificationType.alertaHidrica,
    level: NotificationLevel.emergencia,
    timestamp: DateTime.now().subtract(const Duration(minutes: 12)),
  ),
  NotificationModel(
    id: 'n002',
    title: 'Posible disparo detectado',
    body: 'Nodo N-03 en Norte clasificó disparo con confianza 0.91.',
    barrio: 'Norte',
    type: NotificationType.alertaSeguridad,
    level: NotificationLevel.emergencia,
    timestamp: DateTime.now().subtract(const Duration(minutes: 28)),
  ),
  NotificationModel(
    id: 'n003',
    title: 'Tu reporte está en revisión',
    body: 'El operador recibió tu reporte de robo en Av. Principal.',
    barrio: 'Norte',
    type: NotificationType.reporteEstado,
    timestamp: DateTime.now().subtract(const Duration(hours: 2)),
    isRead: true,
  ),
  NotificationModel(
    id: 'n004',
    title: 'Alerta en barrio suscrito: Centro',
    body: 'Grito humano detectado por nodo C-01 — nivel Alerta.',
    barrio: 'Centro',
    type: NotificationType.alertaSeguridad,
    level: NotificationLevel.alerta,
    timestamp: DateTime.now().subtract(const Duration(hours: 5)),
    isRead: true,
  ),
  NotificationModel(
    id: 'n005',
    title: 'SOS activado cerca de ti',
    body: 'Ciudadano activó SOS de emergencia a 450 m de tu ubicación.',
    barrio: 'Centro',
    type: NotificationType.emergencia,
    level: NotificationLevel.emergencia,
    timestamp: DateTime.now().subtract(const Duration(hours: 8)),
    isRead: true,
  ),
  NotificationModel(
    id: 'n006',
    title: 'Suscripción confirmada: Sur',
    body: 'Recibirás alertas de nivel Alerta y Emergencia en Sur.',
    barrio: 'Sur',
    type: NotificationType.suscripcion,
    timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 3)),
    isRead: true,
  ),
  NotificationModel(
    id: 'n007',
    title: 'Incremento de nivel hídrico',
    body: 'Sensor en Este reporta +2.3 m sobre umbral de Alerta.',
    barrio: 'Este',
    type: NotificationType.alertaHidrica,
    level: NotificationLevel.alerta,
    timestamp: DateTime.now().subtract(const Duration(days: 1, hours: 10)),
    isRead: true,
  ),
  NotificationModel(
    id: 'n008',
    title: 'Reporte atendido',
    body: 'Tu reporte de daño vial en Calle 3 fue marcado como atendido.',
    barrio: 'Sur',
    type: NotificationType.reporteEstado,
    timestamp: DateTime.now().subtract(const Duration(days: 2)),
    isRead: true,
  ),
  NotificationModel(
    id: 'n009',
    title: 'Vehículo sospechoso detectado',
    body: 'Nodo N-01 detectó parada prolongada — nivel Vigilancia.',
    barrio: 'Norte',
    type: NotificationType.alertaSeguridad,
    level: NotificationLevel.vigilancia,
    timestamp: DateTime.now().subtract(const Duration(days: 3)),
    isRead: true,
  ),
  NotificationModel(
    id: 'n010',
    title: 'Bienvenido a Centinela Milagro',
    body:
        'Activa las notificaciones para recibir alertas de tu barrio y los que sigas.',
    barrio: 'Centro',
    type: NotificationType.sistema,
    timestamp: DateTime.now().subtract(const Duration(days: 7)),
    isRead: true,
  ),
];
