// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjELhCh6SK_NGbgZnNHv1NBMFBpVdYjs',
    appId: '1:232951398605:web:47f47d90e1e41674afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    authDomain: 'notifications-8b993.firebaseapp.com',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    measurementId: 'G-WQLNWLV3TN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-qsIfL8V7MG8O9k4MQVIjki6drOx578',
    appId: '1:232951398605:android:5a1c0887d26b02a2afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    storageBucket: 'notifications-8b993.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOS6qtlKXKegozTuvJvpkoztHLEERUfU',
    appId: '1:232951398605:ios:b05843e653dc0538afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    iosBundleId: 'com.example.centinelaMilagro',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVOS6qtlKXKegozTuvJvpkoztHLEERUfU',
    appId: '1:232951398605:ios:b05843e653dc0538afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    iosBundleId: 'com.example.centinelaMilagro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU-IlHyYNKb5ll7xHFSpoBW0pHSDDoWCk',
    appId: '1:232951398605:web:cf17e4be7b9e28e4afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    authDomain: 'notifications-8b993.firebaseapp.com',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    measurementId: 'G-FBJH4FM4YK',
  );
}
