// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZjELhCh6SK_NGbgZnNHv1NBMFBpVdYjs',
    appId: '1:232951398605:web:c6b617ec68b14b56afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    authDomain: 'notifications-8b993.firebaseapp.com',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    measurementId: 'G-QJ6CNQNNDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-qsIfL8V7MG8O9k4MQVIjki6drOx578',
    appId: '1:232951398605:android:124a3b8b69a6d0cfafe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    storageBucket: 'notifications-8b993.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVOS6qtlKXKegozTuvJvpkoztHLEERUfU',
    appId: '1:232951398605:ios:4a8d1aea415c5316afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    iosBundleId: 'com.example.appCine2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVOS6qtlKXKegozTuvJvpkoztHLEERUfU',
    appId: '1:232951398605:ios:4a8d1aea415c5316afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    iosBundleId: 'com.example.appCine2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZjELhCh6SK_NGbgZnNHv1NBMFBpVdYjs',
    appId: '1:232951398605:web:47f47d90e1e41674afe984',
    messagingSenderId: '232951398605',
    projectId: 'notifications-8b993',
    authDomain: 'notifications-8b993.firebaseapp.com',
    storageBucket: 'notifications-8b993.firebasestorage.app',
    measurementId: 'G-WQLNWLV3TN',
  );
}